// Code generated by aru model:build from model.go. DO NOT EDIT.

package fleet

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Fleets starts a query on the table of Fleet, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Fleets(db model.DB) *FleetQuery { return &FleetQuery{b: fleetTable.Query(db)} }

// FleetQuery is a query on the table of Fleet.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Fleet rows or a value; there is
// no way to run one without a Grant.
type FleetQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *FleetQuery) Base() *model.Builder { return q.b }

// New returns an empty Fleet on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *FleetQuery) New() (*Fleet, error) {
	e, err := q.b.NewModelInstance(nil)
	return fleetOf(e), err
}

// FleetCollection is rows of Fleet, as a query returns them.
type FleetCollection []*Fleet

// FleetCollectionOf converts rows of the table of Fleet. A nil input is a nil
// collection.
func FleetCollectionOf(rows model.Rows) FleetCollection {
	if rows == nil {
		return nil
	}
	out := make(FleetCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Fleet)
	}
	return out
}

func fleetOf(e model.Entity) *Fleet {
	row, _ := e.(*Fleet)
	return row
}

// fleetColumn turns a closure over FleetQuery into one over the core builder, so
// passing func(*FleetQuery) where a column goes adds a parenthesised group.
func fleetColumn(column any) any {
	if group, ok := column.(func(*FleetQuery)); ok {
		return func(b *model.Builder) { group(&FleetQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *FleetQuery) Clone() *FleetQuery { return &FleetQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*FleetQuery) in place of the column adds a group.
func (q *FleetQuery) Where(column any, args ...any) *FleetQuery {
	q.b.Where(fleetColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*FleetQuery) in place of the column adds a group.
func (q *FleetQuery) OrWhere(column any, args ...any) *FleetQuery {
	q.b.OrWhere(fleetColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *FleetQuery) WhereNot(column any, args ...any) *FleetQuery {
	q.b.WhereNot(fleetColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *FleetQuery) OrWhereNot(column any, args ...any) *FleetQuery {
	q.b.OrWhereNot(fleetColumn(column), args...)
	return q
}

func (q *FleetQuery) WhereIn(column any, values []any) *FleetQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *FleetQuery) WhereNotIn(column any, values []any) *FleetQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *FleetQuery) WhereNull(columns ...any) *FleetQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *FleetQuery) WhereNotNull(columns ...any) *FleetQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *FleetQuery) WhereBetween(column any, from, to any) *FleetQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *FleetQuery) WhereColumn(first any, args ...any) *FleetQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *FleetQuery) WhereKey(id any) *FleetQuery {
	q.b.WhereKey(id)
	return q
}

func (q *FleetQuery) WhereExists(callback func(*query.Builder)) *FleetQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *FleetQuery) WhereNotExists(callback func(*query.Builder)) *FleetQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *FleetQuery) WhereHas(relation string, callback func(*query.Builder)) *FleetQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *FleetQuery) OrWhereHas(relation string, callback func(*query.Builder)) *FleetQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *FleetQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *FleetQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *FleetQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *FleetQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *FleetQuery) WhereRelation(relation string, column any, args ...any) *FleetQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *FleetQuery) OrWhereRelation(relation string, column any, args ...any) *FleetQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *FleetQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *FleetQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *FleetQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *FleetQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *FleetQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *FleetQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *FleetQuery) OrHas(relation, operator string, count int) *FleetQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *FleetQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *FleetQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *FleetQuery) OrDoesntHave(relation string) *FleetQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *FleetQuery) Select(columns ...any) *FleetQuery {
	q.b.Select(columns...)
	return q
}

func (q *FleetQuery) AddSelect(columns ...any) *FleetQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *FleetQuery) SelectRaw(expression string, bindings ...any) *FleetQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *FleetQuery) Join(table any, first any, args ...any) *FleetQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *FleetQuery) GroupBy(groups ...any) *FleetQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *FleetQuery) OrderBy(column any, direction ...string) *FleetQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *FleetQuery) OrderByDesc(column any) *FleetQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *FleetQuery) Latest(column ...string) *FleetQuery {
	q.b.Latest(column...)
	return q
}

func (q *FleetQuery) Oldest(column ...string) *FleetQuery {
	q.b.Oldest(column...)
	return q
}

func (q *FleetQuery) Limit(value int) *FleetQuery {
	q.b.Limit(value)
	return q
}

func (q *FleetQuery) Offset(value int) *FleetQuery {
	q.b.Offset(value)
	return q
}

func (q *FleetQuery) ForPage(page, perPage int) *FleetQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *FleetQuery) With(relations ...string) *FleetQuery {
	q.b.With(relations...)
	return q
}

func (q *FleetQuery) WithCount(relations ...string) *FleetQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *FleetQuery) WithExists(relation string) *FleetQuery {
	q.b.WithExists(relation)
	return q
}

func (q *FleetQuery) WithSum(relation, column string) *FleetQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *FleetQuery) WithAvg(relation, column string) *FleetQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *FleetQuery) WithMin(relation, column string) *FleetQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *FleetQuery) WithMax(relation, column string) *FleetQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *FleetQuery) Without(relations ...string) *FleetQuery {
	q.b.Without(relations...)
	return q
}

func (q *FleetQuery) WithoutGlobalScope(identifier string) *FleetQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *FleetQuery) WithoutGlobalScopes(identifiers ...string) *FleetQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *FleetQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (FleetCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return FleetCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *FleetQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Fleet, error) {
	e, err := q.b.First(ctx, g, columns...)
	return fleetOf(e), err
}

func (q *FleetQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Fleet, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return fleetOf(e), err
}

func (q *FleetQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Fleet, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return fleetOf(e), err
}

func (q *FleetQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Fleet, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return fleetOf(e), err
}

func (q *FleetQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Fleet, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return fleetOf(e), err
}

func (q *FleetQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Fleet, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return fleetOf(e), err
}

func (q *FleetQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Fleet, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return fleetOf(e), err
}

func (q *FleetQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Fleet, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return fleetOf(e), err
}

func (q *FleetQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (FleetCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return FleetCollectionOf(rows), err
}

func (q *FleetQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Fleet, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return fleetOf(e), err
}

func (q *FleetQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Fleet, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return fleetOf(e), err
}

func (q *FleetQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Fleet, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return fleetOf(e), err
}

func (q *FleetQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Fleet, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return fleetOf(e), err
}

func (q *FleetQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (FleetCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return FleetCollectionOf(rows), meta, err
}

func (q *FleetQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (FleetCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return FleetCollectionOf(rows), meta, err
}

func (q *FleetQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (FleetCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return FleetCollectionOf(rows), meta, err
}

func (q *FleetQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(FleetCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(FleetCollectionOf(rows), page)
	})
}

func (q *FleetQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Fleet, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(fleetOf(e), index)
	})
}

func (q *FleetQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Fleet, error] {
	return func(yield func(*Fleet, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(fleetOf(e), err) {
				return
			}
		}
	}
}

func (q *FleetQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *FleetQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *FleetQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *FleetQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *FleetQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *FleetQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *FleetQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *FleetQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *FleetQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *FleetQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *FleetQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *FleetQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *FleetQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *FleetQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *FleetQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *FleetQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *FleetQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *FleetQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *FleetQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c FleetCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c FleetCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c FleetCollection) Find(key any) *Fleet { return fleetOf(c.Rows().Find(key)) }

func (c FleetCollection) FindOrFail(key any) (*Fleet, error) {
	e, err := c.Rows().FindOrFail(key)
	return fleetOf(e), err
}

func (c FleetCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c FleetCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c FleetCollection) Only(keys ...any) FleetCollection {
	return FleetCollectionOf(c.Rows().Only(keys...))
}

func (c FleetCollection) Except(keys ...any) FleetCollection {
	return FleetCollectionOf(c.Rows().Except(keys...))
}

func (c FleetCollection) Unique() FleetCollection { return FleetCollectionOf(c.Rows().Unique()) }

func (c FleetCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c FleetCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c FleetCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c FleetCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (FleetCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return FleetCollectionOf(rows), err
}

func (c FleetCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Fleet; it shadows the untyped one the
// embedded model promotes.
func (row *Fleet) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Fleet, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return fleetOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Fleet) Replicate(except ...string) (*Fleet, error) {
	e, err := row.Model.Replicate(except...)
	return fleetOf(e), err
}
